### ISSUE TITLE
date limit problem

### ISSUE THREAD

**Issue by Sparviero-Sughero** [arian/mootools-datepicker#169]
there is a bug into "date limit" feature.
if you limit the date from "01-07-2016" and switch the date picker to "Years view", the 2017, 2018, 2019 are disabled.
anyway great work!

**Comment by SergioCrisostomo** [comment]
@Sparviero-Sughero could you make a jsFiddle with a example?
If you want you can adapt this one: https://jsfiddle.net/6d53f3qr/

**Comment by Sparviero-Sughero** [comment]
https://jsfiddle.net/6d53f3qr/2/
