### ISSUE TITLE
Date formatting bug

### ISSUE THREAD

**Issue by rottekruid** [arian/mootools-datepicker#65]
Formatted dates are not read correctly by the datepicker.

E.g. In the legacy test case, the JQuery input uses a formatted date: '%d.%m.%Y %H:%M:%S'. The DatePicker fails to read that format from the input in order to pre-select the relevant date in the picker when opened. (I have also seen this fail with various other date formats that differ from the default date format).

Can be reproduced from the legacy test case as follows:
1. Open this test in browser: https://github.com/arian/mootools-datepicker/blob/master/Test/legacy.html  
2. Click inside "Datepicker with jQuery UI skin:" input to toggle the appearance of the datepicker.
3. Pick a date.
4. The formatted date appears correctly in the input control.
5. Click on the input again to toggle the appearance of the datepicker.
6. The input's (formatted) date is not restored/pre-selected in the datepicker. Instead, the picker default back to 1970 unix epoch due to null date being passed?

**Comment by antajo** [comment]
Try this

You can  replace associate function in datepicker-core.js with this


associate: function(keys) {
        if (keys[0] == "m" && Locale.getCurrent().sets.Date.shortDate.split("-")[0] == "%d") {
            var day = this[0];
            this[0] = this[1];
            this[1] = day;
        }
        if (keys[0] == "m" && Locale.getCurrent().sets.Date.shortDate.split("/")[0] == "%d") {
            var day = this[0];
            this[0] = this[1];
            this[1] = day;
        }
        var obj = {}, length = Math.min(this.length, keys.length);
        for (var i = 0; i < length; i++)
            obj[keys[i]] = this[i];
        return obj;
    }



It worked for me....
