### ISSUE TITLE
Mootools 1.4.1: DatePicker closes after it opened

### ISSUE THREAD

**Issue by BillyBlaze** [arian/mootools-datepicker#96]
For some vague reason the datepicker closes itself immediately after it has been opened.
I fixed this bug/problem with a dirty workaround. (this removes the hook onHide)

At line 155 of Picker.js disable the chain function:

```
picker.fade('out').get('tween').chain(hide);
```

into:

```
picker.fade('out').get('tween');//.chain(hide);
```

**Comment by jarkt** [comment]
Same problem with Mootool 1.6.0. I use the master branch.
